repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.2
  hooks:
    # Run the linter.
    - id: ruff
#      args: [ --fix ] # Automatic correction of errors that Ruff itself can correct