version: '3.9'

services:
  web1:
    build: .
    volumes:
      - ./src:/src # раньше был .:/app
    # В старом варианте весь текущий каталог с хостовой машины (где расположен docker-compose.yaml) монтировался в контейнер в папку /app.
    # В новом варианте теперь на хостовой машине монтируется только папка src, которая находится в том же каталоге, где расположен docker-compose.yaml. В контейнере эта папка монтируется в директорию /src
    # Это означает, что теперь контейнер получает доступ только к содержимому папки src из моего проекта
    environment:
      SERVER_ID: "SERVER-1"
    ports:
      - "8020:8010" # host machine port:container port

  web2:
    build: .
    volumes:
      - ./src:/src
    environment:
      SERVER_ID: "SERVER-2"
    ports:
      - "8021:8010" # host machine port:container port

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2
