services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: chemdb
      POSTGRES_USER: chemuser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "chemuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  web1:
    build: .
    volumes:
      - .:/cont_prj_folder  # Монтируем весь каталог проекта в /cont_prj_folder
    # В старом варианте весь текущий каталог с хостовой машины (где расположен docker-compose.yaml) монтировался в контейнер в папку /app.
    # В новом варианте теперь на хостовой машине монтируется только папка src, которая находится в том же каталоге, где расположен docker-compose.yaml. В контейнере эта папка монтируется в директорию /src
    # Это означает, что теперь контейнер получает доступ только к содержимому папки src из моего проекта
    environment:
      SERVER_ID: "SERVER-1"
    ports:
      - "8020:8010" # host machine port:container port
    depends_on:
      - postgres
#      - redis

  web2:
    build: .
    volumes:
      - .:/cont_prj_folder  # Монтируем весь каталог проекта в /cont_prj_folder
    environment:
      SERVER_ID: "SERVER-2"
    ports:
      - "8021:8010" # host machine port:container port
    depends_on:
      - postgres
#      - redis

#  redis:
#    image: "redis:alpine"
#    ports:
#      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2

volumes:
  pg-data: