version: "3.9"

services:
  fastapi:
    build: .
    ports:
      - "8010:8010" # host machine port:container port
    volumes:
      - .:/app
    command: conda run --no-capture-output -n my-rdkit-env uvicorn src.main:app --host 0.0.0.0 --port 8010 --reload