name: Deploy to EC2

on:
  push:
    branches:
      - main  # Триггер при пуше в основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Обновляем репозиторий
          cd /home/ubuntu/pyforge-python-school-3
          git pull origin main
          
          # Перестраиваем контейнеры
          docker compose down
          docker compose up --build -d
          
          # Проверяем логи
          docker compose logs -f
        EOF
