name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/pyforge-python-school-3
          git pull origin main
          
          docker compose down
          docker compose up --build -d
          
          docker compose logs > deployment_logs.txt
        EOF

    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Deployment Successful"
        body: |
          The deployment to EC2 was successful. 
          Latest code has been pulled, and containers have been restarted.
        to: mesroptnamak@gmail.com
        from: ${{ secrets.EMAIL_USER }}