name: Run tests workflow

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: chemuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: chemdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
          activate-environment: my-rdkit-env
          environment-file: environment.yml
          auto-activate-base: false

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Wait for PostgreSQL
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h localhost -p 5432; do
            sleep 1
          done

      - name: Install dependencies
        run: conda run -n my-rdkit-env conda install -c conda-forge fastapi uvicorn flake8 psycopg2 -y

      - name: Run tests
        run: conda run -n my-rdkit-env pytest tests/

      - name: Run flake8
        run: conda run -n my-rdkit-env flake8 src/ tests/
