# CI (Continuous Integration)
name: Run Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file to set up PostgreSQL connection
      # Variables are placed in Settings > Secrets and variables > Repository secrets
      run: |
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

    - name: Run Ruff linter
      run: |
        docker compose run ruff

    - name: Run tests
      run: |
        docker compose build 
        docker compose up tests
        docker compose down tests

    - name: Publish test status
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./test-reports/
