name: Run tests workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.12
        activate-environment: my-rdkit-env
        auto-update-conda: true
        environment-file: environment.yml

    - name: Install dependencies
      run: |
        conda run -n my-rdkit-env conda list
        conda activate my-rdkit-env

    - name: Run tests
      run: |
        conda run -n my-rdkit-env pytest tests/
