name: Run tests workflow

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: chemuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: chemdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Create and activate virtual environment
        run: |
          python3 -m venv venv_for_rdkit
          source venv_for_rdkit/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source venv_for_rdkit/bin/activate
          pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=postgresql://chemuser:password@localhost:5432/chemdb" >> $GITHUB_ENV

      - name: Install dependencies
        run: conda run -n my-rdkit-env conda install -c conda-forge fastapi uvicorn flake8 psycopg2 -y

      - name: Run tests
        run: |
          source venv_for_rdkit/bin/activate
          pytest tests/

      - name: Run flake8
        run: |
          source venv_for_rdkit/bin/activate
          flake8 src/ tests/