name: Run tests workflow

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
          activate-environment: my-rdkit-env
          environment-file: environment.yml
          auto-activate-base: false

      - name: Install dependencies
        run: conda run -n my-rdkit-env conda install -c conda-forge fastapi uvicorn -y

      - name: Run tests
        run: |
          conda run -n my-rdkit-env pytest tests/
