name: Run tests workflow

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Upgrade pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies (force reinstall and no cache)
        run: |
          python -m pip install --no-cache-dir --force-reinstall -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Run flake8 for static analysis
        run: |
          flake8 src tests
