name: Run tests workflow

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.12
          channels: conda-forge
          use-only-tar-bz2: false

      - name: Create environment and install dependencies
        run: |
          conda create -n my-rdkit-env python=3.12 rdkit=2024.03.4 -c conda-forge -y
          conda install -n my-rdkit-env fastapi uvicorn pytest flake8 -c conda-forge

      - name: Run tests using conda run
        run: |
          conda run -n my-rdkit-env pytest

      - name: Run flake8 for static analysis using conda run
        run: |
          conda run -n my-rdkit-env flake8 src tests
