name: Run tests workflow

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # клонируем код репозитория

      - name: Set up Python 3.12 # гарантирует, что на всех степах используем только Python 3.12 + может потребоваться предустановка для некоторых шагов
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
          activate-environment: my-rdkit-env # активировать my-rdkit-env
          environment-file: environment.yml
          auto-activate-base: false # не активировать (base) по умолчанию

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Install dependencies
        run: conda run -n my-rdkit-env conda install -c conda-forge fastapi uvicorn flake8 -y # Install FastAPI and Uvicorn into my-rdkit-env

      - name: Run tests
        run: conda run -n my-rdkit-env pytest tests/

      - name: Run flake8
        run: conda run -n my-rdkit-env flake8 src/ tests/
