name: Run tests workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.12
        activate-environment: my-rdkit-env
        auto-update-conda: true
        environment-file: environment.yml

    - name: Initialize conda
      shell: bash -l {0}
      run: |
        conda init bash
        source ~/.bashrc

    - name: Install dependencies
      run: |
        conda activate my-rdkit-env
        conda list

    - name: Run tests
      run: |
        conda activate my-rdkit-env
        pytest tests/